### ISSUE TITLE
Incompatible with extra sounds

### ISSUE THREAD

**Issue by Oscillate18** [p4rty4nimAl/enderman-shut#1]
The sliders do not show when the extra sounds mod is installed.

https://www.curseforge.com/minecraft/mc-mods/extrasounds

Could you add compatibility for this please? This is such an amazing qol mod.

![2022-05-22_15 32 40](https://user-images.githubusercontent.com/65877846/169700651-ecfd5f1d-d93c-4ea9-be98-c98f627bcb55.png)
![2022-05-22_15 33 40](https://user-images.githubusercontent.com/65877846/169700656-b2ad8adf-29cd-4a41-acf0-7ad988acba74.png)

**Comment by p4rty4nimAl** [comment]
By looking at the code used to implement ExtraSounds's menus, complete compatibility would be very difficult without unreasonable changes on their end. I will, however, work on a command system which will allow for changing the values that should be compatible.

**Comment by p4rty4nimAl** [comment]
Fixed in 1.1.0

**Comment by Oscillate18** [comment]
Thank you for the workaround, I really appreciate it! Perhaps in the future the slider could be moved to its own menu to avoid compatibility issues, maybe as a config option to give the user choice in keeping the vanilla feel vs its own menu. This is just a suggestion, this solution is more than enough. Thank you for the speedy workaround!
